"""Paired bootstrap test for pairwise model comparisons.

For each (dataset, column, metric), tests whether the F1 / accuracy difference
between two models is significantly different from zero, using the SAME
document-level resampling indices generated by bootstrap_ci.py (so the
comparison is genuinely paired - the same resampled notes evaluate both
models in each bootstrap replicate).

Two-sided paired bootstrap p-value:
    p = 2 * min( P(delta_b >= 0), P(delta_b <= 0) )
clipped to [1/n_boot, 1].

Benjamini-Hochberg FDR adjustment is applied across all (pair, dataset,
column, metric) combinations within each metric family.

Output:
- pvalue_matrix.csv  long-format (pair, dataset, column, metric, delta_point,
  delta_boot_mean, delta_ci_lo, delta_ci_hi, p_value, p_fdr)
- pvalue_summary.json  square matrices per (dataset, column, metric) for
  human inspection of the F1 pairwise grid.

The required main-result pairs from task spec are:
  GPT-4o vs Deepseek, GPT-4o vs Llama, GPT-4o vs Phi
plus GPT-4o vs o3mini (we have predictions for it, include for completeness).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd


DEFAULT_COLUMNS = ['code', 'assertion_status', 'begin_date', 'end_date', 'value', 'unit']
DEFAULT_PAIRS = [
    ('gpt4o', 'deepseek'),
    ('gpt4o', 'llama'),
    ('gpt4o', 'phi4'),
    ('gpt4o', 'o3mini'),
]


def per_replicate_metrics(tp: np.ndarray, fp: np.ndarray, fn: np.ndarray,
                          idx: np.ndarray) -> Dict[str, np.ndarray]:
    tp_boot = tp[idx].sum(axis=1)
    fp_boot = fp[idx].sum(axis=1)
    fn_boot = fn[idx].sum(axis=1)
    with np.errstate(divide='ignore', invalid='ignore'):
        prec = np.where((tp_boot + fp_boot) > 0, tp_boot / (tp_boot + fp_boot), 0.0)
        rec = np.where((tp_boot + fn_boot) > 0, tp_boot / (tp_boot + fn_boot), 0.0)
        denom_f1 = prec + rec
        f1 = np.where(denom_f1 > 0, 2 * prec * rec / denom_f1, 0.0)
        denom_acc = tp_boot + fp_boot + fn_boot
        acc = np.where(denom_acc > 0, tp_boot / denom_acc, 0.0)
    return {'precision': prec, 'recall': rec, 'f1': f1, 'accuracy': acc}


def bh_fdr(pvalues: np.ndarray) -> np.ndarray:
    """Benjamini-Hochberg FDR adjustment. Returns adjusted p-values (q-values)."""
    n = len(pvalues)
    if n == 0:
        return pvalues.copy()
    order = np.argsort(pvalues)
    ranks = np.empty(n, dtype=int)
    ranks[order] = np.arange(1, n + 1)
    adjusted = pvalues * n / ranks
    # enforce monotonicity
    sorted_idx = np.argsort(pvalues)
    sorted_adj = adjusted[sorted_idx]
    sorted_adj = np.minimum.accumulate(sorted_adj[::-1])[::-1]
    sorted_adj = np.minimum(sorted_adj, 1.0)
    out = np.empty(n)
    out[sorted_idx] = sorted_adj
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--counts', required=True)
    ap.add_argument('--resamples', required=True,
                    help='bootstrap_resamples.npz from bootstrap_ci.py')
    ap.add_argument('--out-dir', required=True)
    ap.add_argument('--columns', nargs='+', default=DEFAULT_COLUMNS)
    ap.add_argument('--metrics', nargs='+', default=['f1', 'accuracy'])
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(args.counts) as f:
        counts = json.load(f)

    resamples = np.load(args.resamples)

    rows: List[Dict] = []

    # For paired bootstrap, both models in the pair must have the same
    # note set within a given dataset. If models have different note sets
    # (e.g. phi4 is matched-only), we intersect the note_ids and rebuild
    # the resample matrix for the intersection using the canonical seed
    # offset; record n_notes so reader can see the comparison set size.
    for model_a, model_b in DEFAULT_PAIRS:
        if model_a not in counts or model_b not in counts:
            print(f"skip pair ({model_a}, {model_b}) - missing counts")
            continue
        for ds in counts[model_a]:
            if ds not in counts[model_b]:
                continue
            notes_a = sorted(counts[model_a][ds].keys())
            notes_b = sorted(counts[model_b][ds].keys())
            common = sorted(set(notes_a) & set(notes_b))
            if not common:
                continue

            # build per-note arrays for the common set (in alpha order)
            def build_arrs(model, notes):
                out_arrs = {}
                for col in args.columns:
                    tps = np.array([counts[model][ds][n].get(col, {'tp': 0})['tp'] for n in notes],
                                   dtype=np.int64)
                    fps = np.array([counts[model][ds][n].get(col, {'fp': 0})['fp'] for n in notes],
                                   dtype=np.int64)
                    fns = np.array([counts[model][ds][n].get(col, {'fn': 0})['fn'] for n in notes],
                                   dtype=np.int64)
                    out_arrs[col] = (tps, fps, fns)
                return out_arrs

            arrs_a = build_arrs(model_a, common)
            arrs_b = build_arrs(model_b, common)

            # Use canonical resample indices if exact note list matches the
            # full-set indices saved by bootstrap_ci.py; otherwise rebuild
            # with a deterministic per-pair seed.
            full_a_key = f"{model_a}__{ds}"
            if full_a_key in resamples and len(common) == len(notes_a) == len(notes_b) and common == notes_a == notes_b:
                idx = resamples[full_a_key]
            else:
                # rebuild deterministic indices keyed by note ids
                # seed = stable hash of (ds, common). For matched-only cases
                # like phi4, we re-bootstrap on common only with a seed that
                # is reproducible.
                seed_str = f"{ds}|{'|'.join(common)}"
                seed = abs(hash(seed_str)) % (2 ** 32)
                n_boot = next(iter(resamples.values())).shape[0]
                rng = np.random.default_rng(seed)
                idx = rng.integers(0, len(common), size=(n_boot, len(common)))

            for col in args.columns:
                tp_a, fp_a, fn_a = arrs_a[col]
                tp_b, fp_b, fn_b = arrs_b[col]
                # point estimate delta
                def point(tp, fp, fn):
                    p = tp.sum() / (tp.sum() + fp.sum()) if tp.sum() + fp.sum() > 0 else 0.0
                    r = tp.sum() / (tp.sum() + fn.sum()) if tp.sum() + fn.sum() > 0 else 0.0
                    f1 = 2*p*r/(p+r) if (p+r) > 0 else 0.0
                    acc = tp.sum() / (tp.sum() + fp.sum() + fn.sum()) if (tp.sum() + fp.sum() + fn.sum()) > 0 else 0.0
                    return {'precision': p, 'recall': r, 'f1': f1, 'accuracy': acc}

                pt_a = point(tp_a, fp_a, fn_a)
                pt_b = point(tp_b, fp_b, fn_b)
                met_a = per_replicate_metrics(tp_a, fp_a, fn_a, idx)
                met_b = per_replicate_metrics(tp_b, fp_b, fn_b, idx)

                for metric in args.metrics:
                    delta_point = float(pt_a[metric] - pt_b[metric])
                    delta_boot = met_a[metric] - met_b[metric]
                    delta_mean = float(delta_boot.mean())
                    delta_ci_lo = float(np.percentile(delta_boot, 2.5))
                    delta_ci_hi = float(np.percentile(delta_boot, 97.5))
                    n_boot = len(delta_boot)
                    # two-sided paired bootstrap p-value
                    p_ge = float(np.mean(delta_boot >= 0))
                    p_le = float(np.mean(delta_boot <= 0))
                    raw_p = 2.0 * min(p_ge, p_le)
                    raw_p = max(raw_p, 1.0 / n_boot)
                    raw_p = min(raw_p, 1.0)
                    rows.append({
                        'model_a': model_a,
                        'model_b': model_b,
                        'dataset': ds,
                        'column': col,
                        'metric': metric,
                        'n_common_notes': len(common),
                        'n_boot': n_boot,
                        'delta_point': delta_point,
                        'delta_boot_mean': delta_mean,
                        'delta_ci_lo': delta_ci_lo,
                        'delta_ci_hi': delta_ci_hi,
                        'p_value': raw_p,
                    })

    df = pd.DataFrame(rows)
    # FDR per metric family across all pairs/datasets/columns
    df['p_fdr'] = np.nan
    for metric in df['metric'].unique():
        mask = df['metric'] == metric
        df.loc[mask, 'p_fdr'] = bh_fdr(df.loc[mask, 'p_value'].values)

    df.to_csv(out_dir / 'pvalue_matrix.csv', index=False)
    print(f"Wrote {out_dir / 'pvalue_matrix.csv'}")

    # human-readable F1 pairwise summary
    summary: Dict = {}
    for (ds, col, metric), sub in df.groupby(['dataset', 'column', 'metric']):
        d_key = f"{ds}|{col}|{metric}"
        summary[d_key] = {
            f"{r.model_a}_vs_{r.model_b}": {
                'delta_point': round(r.delta_point, 4),
                'delta_ci': [round(r.delta_ci_lo, 4), round(r.delta_ci_hi, 4)],
                'p_value': round(r.p_value, 5),
                'p_fdr': round(r.p_fdr, 5),
                'n_common_notes': int(r.n_common_notes),
            } for r in sub.itertuples(index=False)
        }
    with open(out_dir / 'pvalue_summary.json', 'w') as f:
        json.dump(summary, f, indent=2)
    print(f"Wrote {out_dir / 'pvalue_summary.json'}")

    # screen summary: F1 deltas vs GPT-4o
    print("\n--- F1 pairwise: GPT-4o vs others (delta_point [95% CI], p, p_FDR) ---")
    f1_only = df[df['metric'] == 'f1'].sort_values(['model_b', 'dataset', 'column'])
    for _, r in f1_only.iterrows():
        sig = '*' if r['p_fdr'] < 0.05 else ' '
        print(f"  {sig} {r['model_a']:<8} vs {r['model_b']:<8} "
              f"{r['dataset']:<16} {r['column']:<18} "
              f"d={r['delta_point']:+.3f} [{r['delta_ci_lo']:+.3f}, {r['delta_ci_hi']:+.3f}]  "
              f"p={r['p_value']:.4f}  p_FDR={r['p_fdr']:.4f}  n={r['n_common_notes']}")


if __name__ == '__main__':
    main()
